/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Quick' at '7/23/16 4:00 AM' with Gradle 2.13
 *
 * @author Quick, @date 7/23/16 4:00 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
